### ISSUE TITLE
Docs point to cppproperties.silizium.io

### ISSUE THREAD

**Issue by bryceschober** [Tectu/cpp-properties#6]

**Comment by Tectu** [comment]
Hey,

Where exactly did you come across this link? The docs are currently available at https://cppproperties.insane.engineer/. Still WIP tho. Is there an old link somwewhere I missed?

**Comment by bryceschober** [comment]
Sorry, I guess I filed it against the wrong repo: https://github.com/Tectu/cpp-properties-website/search?q=cppproperties.silizium.io

**Comment by Tectu** [comment]
Yep, that is a separate repository :)

I've updated the references. Thank you for reporting this!
